export const ORGAN_IMAGE_MAP: Record<string, string> = {
  'cerebro': 'https://i.postimg.cc/2bPk7tJk/cerebro.png',
  'colon': 'https://i.postimg.cc/HJvsVn9L/colon.png',
  'estomago': 'https://i.postimg.cc/LYr93W75/estomago.png',
  'higado': 'https://i.postimg.cc/TLy2mxtk/higado.png',
  'huesos_pierna': 'https://i.postimg.cc/21w5N2qv/huesos-d-la-pierna.png',
  'huesos_brazo': 'https://i.postimg.cc/Hr2L1BJb/huesos-del-brazo.png',
  'ovarios': 'https://i.postimg.cc/hJZPfv1P/ovarios.png',
  'pancreas': 'https://i.postimg.cc/06X2bj0n/pancreas.png',
  'piel': 'https://i.postimg.cc/CZxxhkkx/piel.png',
  'prostata': 'https://i.postimg.cc/CZrLz5sh/prostata.png',
  'pulmones': 'https://i.postimg.cc/9zRzwdS7/pulmones.png',
  'rinones': 'https://i.postimg.cc/67b5yqfz/rinones.png',
  'senos': 'https://i.postimg.cc/7GCP74KW/senos.png',
  'testiculos': 'https://i.postimg.cc/d7VVsrrk/testiculos.png',
  'tiroides': 'https://i.postimg.cc/ph7T1r9v/tiroides.png',
  'vejiga': 'https://i.postimg.cc/TyNYp1J2/vejiga.png',
};

export const ORGAN_K_MAP: Record<string, number> = {
  'Cerebro': 300,
  'Tiroides': 150,
  'Pulmón Derecho': 500,
  'Pulmón Izquierdo': 500,
  'Seno Derecho': 400,
  'Seno Izquierdo': 400,
  'Hígado': 800,
  'Estómago': 600,
  'Riñón Derecho': 450,
  'Riñón Izquierdo': 450,
  'Páncreas': 350,
  'Colon': 700,
  'Ovarios': 350,
  'Próstata': 300,
  'Testículos': 250,
  'Vejiga': 500,
  'Huesos (Brazo)': 300,
  'Huesos (Pierna)': 500,
  'Piel': 200,
};
